name: Deploy to gh-pages

on:
  merge:
    branches: [main]
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Build site
        run: npm run build

      - name: Copy CNAME
        run: cp ./CNAME ./dist/

      - name: Create 404.html for SPA routing
        run: |
          cat > ./dist/404.html << EOL
          <!DOCTYPE html>
          <html>
          <head>
            <meta charset="utf-8">
            <title>Redirecting...</title>
            <script>
              sessionStorage.setItem('redirect', window.location.pathname);
              window.location.href = '/';
            </script>
          </head>
          <body>
            <p>Redirecting...</p>
          </body>
          </html>
          EOL

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist